const LOAD_USER_RECORDS = 'LOAD_USER_RECORDS';
const LOAD_USER_RECORDS_SUCCESS = 'LOAD_USER_RECORDS_SUCCESS';
const LOAD_USER_RECORDS_ERROR = 'LOAD_USER_RECORDS_ERROR';

const SEARCH_FILTER_RECORDS = 'SEARCH_FILTER_RECORDS';
const DROP_DOWN_FILTER_RECORDS = 'DROP_DOWN_FILTER_RECORDS';

export {
    LOAD_USER_RECORDS,
    LOAD_USER_RECORDS_SUCCESS,
    LOAD_USER_RECORDS_ERROR,
    SEARCH_FILTER_RECORDS,
    DROP_DOWN_FILTER_RECORDS
}